### ISSUE TITLE
Information regarding ref tables masking during extract

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#335] opened 2021-10-13 15:26 UTC
Hello,

With reference to link https://support.k2view.com/Academy_6.5/articles/TDM/tdm_architecture/05_tdm_reference_processes.html#:~:text=tdmCopyRefTablesForTDM which describes the ref extract process in general , I would like to know how would it be possible to support a masking use case for ref table extract. The expectation is to store masked ref data in cassandra too.

Regards,
Prathamesh

**Comment by taliei** [comment] 2021-10-14 05:55
Hi.

tdmCopyRefTablesForTDM job copies the ref table "as is" to Cassandra. What is the business use case to mask reference data? Reference tables store metadata or operational data like billing cycle code, or customer type. The data needs to be copied with the real values to the testing environment. These tables do not store a personal data of a customer.

So- why do we need to mask their values? Moreover, if the values of the reference tables are masked, they become unusable. For example, if you replace the values of the cycle codes, they will not be aligned with the cycle codes of the customers.

Regards,
Tali

**Comment by prathameshpalaskark2view** [comment] 2021-10-14 18:46
Hi Tali,

Yes that is the standard definition of a reference table. your understanding is also correct.  As far as I understand, there is no active masking development in the project but its a scenario that may come up in the project where even if its not personal data , due to data governance rules, some of the column data might need to be masked. 
Regards,
Prathamesh

**Comment by taliei** [comment] 2021-10-17 15:40
Hi.

Closing the ticket. This is the system behaviour by design. If in the future there is a business need to enable masking on reference data, open a new ticket to reevaluate it.

Thanks,
Tali

**Closed as completed by taliei** 2021-10-17 15:40 UTC
