### ISSUE TITLE
Fabric's Kafka clients (producer/consumer) connections behavious and configurations

### ISSUE THREAD

**Issue by ignacio-butler-42** [k2view-academy/K2View-Academy#1189] opened 2024-11-07 09:48 UTC
In recent versions of the Kafka client libraries, there was a major change in the [default Kafka producer clients](https://kafka.apache.org/documentation/#upgrade_320_notable) configurations (properties). The setting in question is [`enable.idempotence`](https://kafka.apache.org/documentation/#producerconfigs_enable.idempotence) is for producers and its effect in the Kafka brokers is the servers will keep track of the clients (client_id) to ensure these won't send duplicate messages so that exactly one is delivered.

With this setting set to true by default, it becomes important Fabric doesn't create too many clients to prevent **impacting the performance** of the Kafka servers.

Therefore, the questions are:

* How does Fabric create Kafka Producers in the CDC flows (if any)? How the client ids are decided?
* Are the Kafka producers immediatly destroyed or are they reused?
* When using Broadway Producer actors, are the clients created immediately or they are obtained from a *pool*? How their client ids are defined? Which would be their lifecycle within a flow?
* When implementing Java functions, is there a preferred/provided way to obtain clients (consumers or producers) from configured interfaces?

Additionally:

* Would it be ok for the provided functionality to disable producer's idempotency or would it have any impact on the provided consumers?
* Is it possible to add additional properties in the configurations for these *additional* configurations that the consumers and/or producer might have around the interfaces/fabric/iidfinder? A rather more broad mechanism for additional configurations.

Thank you in advance,

**Comment by natalylic** [comment] 2024-11-10 15:15
1. Impact of Kafka Client Configuration Changes (Idempotence Parameter):
Since the `enable.idempotence` parameter is explicitly set to true in our API, this Kafka client configuration change won’t impact our Kafka API functionality. The idempotence behavior has already been enforced in previous versions, ensuring exactly-once delivery.
2. How Does Fabric Create Kafka Producers in the CDC Flows? How Are Client IDs Decided?
CDC uses PubSub’s transactions to create Kafka Producers in the CDC Flows. The producer's lifetime is being managed by the PubSub as well.
4. Are the Kafka Producers Immediately Destroyed or Reused?
If a producer is created with the same configuration or interface and pooling is enabled (enabled by default), then producers are reused rather than destroyed, minimizing the overhead of re-initializing producers.
5. When Using Broadway Producer Actors, Are Clients Created Immediately or Obtained from a Pool?
The first instance of a Broadway Producer actor creates a new producer. However, if the same producer instance is created with the same interface and pooling is enabled, that producer will be reused rather than creating new instances repeatedly.
6. How Are Client IDs Defined? What is Their Lifecycle Within a Flow?
If a client.id is not explicitly configured in the config.ini file, Kafka generates a unique client.id for each producer. The lifecycle of the producer remains active and reused within the flow as long as the same configuration and pooling are in place.

7. Preferred Method for Obtaining Clients (Consumers or Producers) in Java Functions?
There is no additional setup required for consumers or producers regarding the enable.idempotence parameter, as it has been explicitly set to true in the API across versions. This ensures the Kafka API functions consistently with idempotence enabled, without any changes needed in Java function implementations.

8. Is it Acceptable to Disable Producer’s Idempotency? Would It Impact Consumers?
Disabling idempotence is not an option since it is set explicitly to true within the API, ensuring exactly-once semantics and preventing duplicate message delivery to consumers.

9. Can Additional Properties Be Configured for Producers and Consumers (Interface/Fabric/IIDFinder)?
Yes, most Kafka properties can be configured in the config.ini under the pubsub section, providing a broad mechanism for customization. However, some parameters, like enable.idempotence, are fixed by design for consistent behavior.

**Comment by ignacio-butler-42** [comment] 2024-11-11 09:07
Hello, 

Thanks for the feedback, though I need couple more clarifications:

> 2. How Does Fabric Create Kafka Producers in the CDC Flows? How Are Client IDs Decided?
> CDC uses PubSub’s transactions to create Kafka Producers in the CDC Flows. The producer's lifetime is being managed by the PubSub as well.

I'm not exactly sure what this means in practical terms; mind expanding? Also, what about the client ids? 

> 5. How Are Client IDs Defined? What is Their Lifecycle Within a Flow?
> If a client.id is not explicitly configured in the config.ini file, Kafka generates a unique client.id for each producer. The lifecycle of the producer remains active and reused within the flow as long as the same configuration and pooling are in place.

Client ids in Kafka clients, are meant to be used for traceability; meaning it could be useful to define a client_id per Broadway flow. Is there a way to explicitly define them when creating a Publish actor?

> 8.Can Additional Properties Be Configured for Producers and Consumers (Interface/Fabric/IIDFinder)?
> Yes, most Kafka properties can be configured in the config.ini under the pubsub section, providing a broad mechanism for customization. However, some parameters, like enable.idempotence, are fixed by design for consistent behavior.

Which would be the configuration format to define client's properties? I've no sample in the default config.ini. Say for example if I want to tune the producer client's retries property.

Thank you in advance,

**Comment by omernissan** [comment] 2024-11-11 10:47
As Nataly mentioned, we do not explicitly specify a client.id when creating producers. In such cases, Kafka automatically assigns a default value in the format producer-<unique-id>.

However, when a new producer is created in transaction mode (as in CDC flows), we explicitly set the transactional.id. In this mode, Kafka brokers primarily rely on the transactional.id to maintain producer state, rather than the client.id.

Currently, we utilize a producer pool for transaction producers. This means producers can be reused across flows, reducing overhead associated with creating and closing producers frequently. Each producer in the pool retains its unique transactional.id.

_Do you want to control the client.id?_
If so, what is the primary purpose? For example, are you looking for better monitoring, debugging, or resource tracking?
Are you observing any specific issues related to the client.id or the current producer configuration?

For transactional producers, the following properties are currently hardcoded:
transactional.id
enable.idempotence: Set to true 
acks: Configured to all to ensure data durability.
retries: Set to 3 to handle transient failures.

**Comment by ignacio-butler-42** [comment] 2024-11-11 11:02
Hello,

> Are you observing any specific issues related to the client.id or the current producer configuration?

Indeed, having multiple _randomly generated_ client.ids in Kafka brokers increases the pressure in the Kafka nodes as they have to persist the individual client ids for a period of time to ensure idempotency causing performance issues on the Kafka server itself.

Moreover, having different client ids from the same _client_ is something we want to prevent, as otherwise, it defeats the idempotency purpose.

Thus:

1. I'm not sure still if the transactional.id is the correct approach or not; though it seems it is.
2. Need the ability to control this from a Broadway flow. Is there a way to set it?

Best regards,

**Comment by omernissan** [comment] 2024-11-11 11:11
By reusing producers from the pool, we avoid creating multiple unique producers with different randomly generated client.id values.

Since our pool ensures that each producer retains its transactional.id throughout its lifecycle, even if the client.id is random, the idempotency guarantees remain intact.

Why do you need the ability to control the client.id?

**Comment by ignacio-butler-42** [comment] 2024-11-11 11:16
It is good to know the CDC is covered.

The reason we need this control in Broadway is two fold: reduce the performance impact on the kafka server, and the traceability capabilities it provides.

**Closed as completed** 2024-11-12 14:44 UTC
